# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HOIH' do
pod 'AFNetworking'
end

target 'HOIHTests' do

end

target 'HOIHUITests' do

end

